### ISSUE TITLE
Support for blur on thumbnails

### ISSUE THREAD

**Issue by ahanriat** [react-native-toolkit/react-native-better-image#5]
Hi 👋 

Great library 👏 

I was wondering if you were interested in having a PR **adding a blur effect** on top of the thumbnail image allowing for very low res base64 images?

Note that this would add a dependency to https://github.com/react-native-community/react-native-blur

Let me know what you think 🤗

**Comment by DaniAkash** [comment]
I'm currently using `blurRadius` prop of the `Image` component to blur the thumbnails. You can configure this using the [`thumbnailBlurRadius`](https://betterimage.netlify.app/?path=/story/intro-api-reference--page#thumbnailblurradius-number) prop. I have tried it with very low res images and so far they have been working properly.

I'd like to understand why I should be using react-native-blur to achieve a similar effect...

**Comment by ahanriat** [comment]
My bad I've read this too fast ;) 

I'm closing the issue 💨
